#!/bin/sh /etc/rc.common
START=91

start ()  {
      if ! [ -f /etc/nodeid ]; then
        batctl o | head -1 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}' | md5sum | cut -f1 -d' ' > /etc/nodeid
      fi
}
